{
  configurations.nixos.krypton = {pkgs, ...}: {
    programs.nix-ld = {
      enable = true;
      libraries = with pkgs; [
        stdenv.cc.cc
        coreutils
        util-linux
        systemd
        zlib
        zstd
        xz
        bzip2
        acl
        attr
        fuse
        fuse3
        e2fsprogs
        libxml2
        libelf
        libuuid
        libsodium
        libxcrypt
        libxcrypt-legacy
        keyutils
        icu
        gmp
        expat
        gtk2
        gtk3
        glib
        dbus
        dbus-glib
        gdk-pixbuf
        cairo
        pango
        harfbuzz
        atk
        at-spi2-atk
        at-spi2-core
        libnotify
        zenity
        libappindicator-gtk2
        libappindicator-gtk3
        libdbusmenu
        libdbusmenu-gtk2
        libindicator-gtk2
        desktop-file-utils
        gsettings-desktop-schemas
        libsecret
        xorg.libX11
        xorg.libXcomposite
        xorg.libXcursor
        xorg.libXdamage
        xorg.libXext
        xorg.libXfixes
        xorg.libXft
        xorg.libXi
        xorg.libXinerama
        xorg.libXmu
        xorg.libXrandr
        xorg.libXrender
        xorg.libXScrnSaver
        xorg.libXt
        xorg.libXtst
        xorg.libXxf86vm
        xorg.libxcb
        xorg.libxshmfence
        xorg.libpciaccess
        xorg.xcbutil
        xorg.xcbutilimage
        xorg.xcbutilkeysyms
        xorg.xcbutilrenderutil
        xorg.xcbutilwm
        xorg.xkeyboardconfig
        libxkbcommon
        wayland
        mesa
        libGL
        libGLU
        libglvnd
        libgbm
        libdrm
        libva
        libvdpau
        vulkan-loader
        freeglut
        glew_1_10
        libcaca
        pipewire
        libpulseaudio
        libjack2
        alsa-lib
        ffmpeg
        gst_all_1.gstreamer
        gst_all_1.gst-plugins-base
        gst_all_1.gst-plugins-ugly
        libmikmod
        libogg
        libvorbis
        libtheora
        libvpx
        flac
        speex
        libsamplerate
        libcanberra
        libpng
        libpng12
        libjpeg
        libtiff
        fontconfig
        freetype
        fribidi
        librsvg
        libthai
        pixman
        tbb
        SDL
        SDL2
        SDL2_image
        SDL2_mixer
        SDL2_ttf
        SDL_image
        SDL_mixer
        SDL_ttf
        libudev0-shim
        curl
        openssl
        nspr
        nss
        libssh
        libidn
        libcap
        libgcrypt
        libgpg-error
        libusb1
        pciutils
        networkmanager
        cups
        python3
        libclang.lib
      ];
    };
  };
}
